FROM golang:1.17.4-alpine3.15 as builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ripe

# final stage
FROM scratch
COPY --from=builder /app/ripe /app/
EXPOSE 8123
CMD ["/app/ripe"]
ENTRYPOINT ["/app/ripe", "run", "client", "--grpc.host", "127.0.0.1", "--grpc.port", "8123"]