// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: ripe.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The response message containing the greetings
type RIS_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RIS_Message) Reset() {
	*x = RIS_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ripe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RIS_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RIS_Message) ProtoMessage() {}

func (x *RIS_Message) ProtoReflect() protoreflect.Message {
	mi := &file_ripe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RIS_Message.ProtoReflect.Descriptor instead.
func (*RIS_Message) Descriptor() ([]byte, []int) {
	return file_ripe_proto_rawDescGZIP(), []int{0}
}

func (x *RIS_Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RIS_Message) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ripe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ripe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ripe_proto_rawDescGZIP(), []int{1}
}

var File_ripe_proto protoreflect.FileDescriptor

var file_ripe_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x69, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x52, 0x69,
	0x70, 0x65, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x0b, 0x52, 0x49, 0x53, 0x5f,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x40, 0x0a, 0x04, 0x52, 0x69, 0x70, 0x65,
	0x12, 0x38, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x2e, 0x52, 0x69, 0x70,
	0x65, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x49, 0x53, 0x5f, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x11, 0x2e, 0x52, 0x69, 0x70, 0x65, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ripe_proto_rawDescOnce sync.Once
	file_ripe_proto_rawDescData = file_ripe_proto_rawDesc
)

func file_ripe_proto_rawDescGZIP() []byte {
	file_ripe_proto_rawDescOnce.Do(func() {
		file_ripe_proto_rawDescData = protoimpl.X.CompressGZIP(file_ripe_proto_rawDescData)
	})
	return file_ripe_proto_rawDescData
}

var file_ripe_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ripe_proto_goTypes = []interface{}{
	(*RIS_Message)(nil), // 0: RipeIngest.RIS_Message
	(*Empty)(nil),       // 1: RipeIngest.Empty
}
var file_ripe_proto_depIdxs = []int32{
	0, // 0: RipeIngest.Ripe.Stream:input_type -> RipeIngest.RIS_Message
	1, // 1: RipeIngest.Ripe.Stream:output_type -> RipeIngest.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ripe_proto_init() }
func file_ripe_proto_init() {
	if File_ripe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ripe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RIS_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ripe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ripe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ripe_proto_goTypes,
		DependencyIndexes: file_ripe_proto_depIdxs,
		MessageInfos:      file_ripe_proto_msgTypes,
	}.Build()
	File_ripe_proto = out.File
	file_ripe_proto_rawDesc = nil
	file_ripe_proto_goTypes = nil
	file_ripe_proto_depIdxs = nil
}
